version: "3.7"
services:

  alienmw.local-db:
    container_name: alienmw.local-db
    image: mariadb:latest
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "a113na113n"
      MYSQL_DATABASE: alienmw
    volumes:
      - /Users/rubyon/docker/alienmw/mysql:/var/lib/mysql

networks:
  frontend:
  backend:
